version: '3'
services:
  nginx:
    image: nginx:alpine
    ports:
      - "8123:8123"
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - ./data/nginx/conf.d:/etc/nginx/conf.d
      - ./data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./data/nginx/exclusion-rules.conf:/opt/owasp-crs/rules/RESPONSE-999-EXCLUSION-RULES-AFTER-CRS.conf
      - ./data/nginx/GeoIP:/usr/share/GeoIP/
      - ./data/certbot:/etc/letsencrypt
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  certbot:
    image: certbot/certbot:arm32v6-latest
    volumes:
      - ./data/certbot:/etc/letsencrypt
      - ./duckdns-hook.sh:/duckdns-hook.sh
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

